package com.infernodude777.endesium.client.datagen;

import com.infernodude777.endesium.registry.ModBlocks;
import com.infernodude777.endesium.registry.ModItems;
import java.util.concurrent.CompletableFuture;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;

public final class EndesiumLanguageProvider extends FabricLanguageProvider {

	public EndesiumLanguageProvider(FabricDataOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
		super(dataOutput, registryLookup);
	}

	@Override
	public void generateTranslations(HolderLookup.Provider registryLookup, TranslationBuilder translationBuilder) {
		translationBuilder.add(ModItems.VOID_SHARD, "Void Shard");
		translationBuilder.add(ModItems.ENDESIUM_GUIDEBOOK, "Endesium Guidebook");
		translationBuilder.add(ModItems.PROGRESSION_GUIDE, "Endesium Progression Guide");
		translationBuilder.add(ModItems.RESONANCE_LENS, "Resonance Lens");
		translationBuilder.add(ModItems.RESONANT_WINGS, "Resonant Elytra");
		translationBuilder.add(ModItems.RESONANT_DRAGON_SCALE, "Resonant Dragon Scale");
		translationBuilder.add(ModItems.DRAGONBONE, "Dragonbone");
		translationBuilder.add(ModItems.DRAGON_FANG, "Dragon Fang");
		translationBuilder.add(ModItems.DRAGON_HEART, "Dragon Heart");
		translationBuilder.add(ModItems.ENDER_ESSENCE, "Ender Essence");
		translationBuilder.add(ModItems.ECHO_SHARD, "Resonance Echo");
		translationBuilder.add(ModItems.VOID_PEARL, "Void Pearl");
		translationBuilder.add(ModItems.ABYSSAL_THREAD, "Abyssal Thread");
		translationBuilder.add(ModItems.RESONANCE_CORE, "Resonance Core");
		translationBuilder.add(ModItems.ARCHIVE_FRAGMENT, "Archive Fragment");
		translationBuilder.add("key.categories.endesium", "Endesium");
		translationBuilder.add("key.endesium.sonic_boom", "Sonic Boom");

		// Dragon fight phase titles/subtitles (transformed and first-fight arcs).
		translationBuilder.add("endesium.dragon.awakened.phase1.title", "The Awakened Watches");
		translationBuilder.add("endesium.dragon.awakened.phase1.subtitle", "It remembers you");
		translationBuilder.add("endesium.dragon.awakened.phase2.title", "The Awakened Hunts");
		translationBuilder.add("endesium.dragon.awakened.phase2.subtitle", "Resonance sharpens its ancient hunt");
		translationBuilder.add("endesium.dragon.awakened.phase3.title", "The Deep Resonance Trembles");
		translationBuilder.add("endesium.dragon.awakened.phase3.subtitle", "The island remembers its wounds");
		translationBuilder.add("endesium.dragon.awakened.phase4.title", "The End's Eternal Fury");
		translationBuilder.add("endesium.dragon.awakened.phase4.subtitle", "Nothing was ever held back");
		translationBuilder.add("endesium.dragon.phase1.title", "The Dragon Watches");
		translationBuilder.add("endesium.dragon.phase2.title", "The Dragon Hunts");
		translationBuilder.add("endesium.dragon.phase2.subtitle", "Resonance sharpens its hunting");
		translationBuilder.add("endesium.dragon.phase3.title", "The Wastes Tremble");
		translationBuilder.add("endesium.dragon.phase3.subtitle", "The island answers the wounds");
		translationBuilder.add("endesium.dragon.phase4.title", "The End's Fury");
		translationBuilder.add("endesium.dragon.phase4.subtitle", "Nothing is held back");

		// Post-Dragon transformation and boss reward feedback.
		translationBuilder.add("endesium.event.something_older_stirs", "Something Older Stirs");
		translationBuilder.add("endesium.event.golem_wakes", "The Golem wakes where the dragon fell");
		translationBuilder.add("endesium.golem_resolve.saved", "The golem's core holds your soul together. Until tomorrow.");
		translationBuilder.add("endesium.golem_core.maxed", "You are already more than the golem ever was.");
		translationBuilder.add("endesium.golem_core.absorbed", "The core collapses into your chest. You feel heavier, and stronger.");
		translationBuilder.add("endesium.golem_core.resolve_unlocked", "GOLEM'S RESOLVE — death itself will hesitate. Once a day.");
		translationBuilder.add("endesium.sigil.maxed", "Your soul can hold no more of the wardens' light.");
		translationBuilder.add("endesium.sigil.attuned", "The sigil burns into your soul. +%s heart(s), forever.");
		translationBuilder.add("endesium.sigil.ascendant", "WARDEN ASCENDANT — every region's light lives in you now.");
		translationBuilder.add("endesium.effigy.wrong_dimension", "The effigy is silent. It answers only to the End.");
		translationBuilder.add("endesium.effigy.golem_exists", "A golem already walks. It must fall first.");
		translationBuilder.add("endesium.effigy.no_ground", "The stone finds no purchase here. Seek open ground.");
		translationBuilder.add("endesium.effigy.wakes", "The effigy crumbles. The engine wakes.");
		translationBuilder.add(ModItems.RESONANCE_TOKEN, "Resonance Token");
		translationBuilder.add(ModItems.ECHO_COMPASS, "Echo Compass");
		translationBuilder.add(ModItems.ARCHIVE_SIGIL, "Archive Sigil");
		translationBuilder.add(ModBlocks.RESONANT_SLATE, "Resonant Slate");
		translationBuilder.add(ModBlocks.END_GRAY, "End Gray");
		translationBuilder.add(ModBlocks.DORMANT_RESONANT_CRYSTAL, "Dormant Resonant Crystal");
		translationBuilder.add(ModBlocks.RESONANT_MECHANISM, "Resonant Mechanism");
		translationBuilder.add(ModBlocks.CHORUS_SPROUT, "Chorus Sprout");
		translationBuilder.add(ModBlocks.WILD_TENDRIL, "Wild Tendril");
		translationBuilder.add(ModBlocks.RESONANT_BLOOM, "Resonant Bloom");
		translationBuilder.add(ModBlocks.INSCRIBED_SLATE, "Inscribed Slate");
		translationBuilder.add(ModBlocks.RESONANT_PILLAR, "Resonant Pillar");
		translationBuilder.add(ModBlocks.CRACKED_SPIRE_STONE, "Cracked Spire Stone");
		translationBuilder.add(ModBlocks.WASTES_STONE, "Wastes Stone");
		translationBuilder.add(ModBlocks.WASTES_GRAVEL, "Wastes Gravel");
		translationBuilder.add(ModBlocks.DUST_REED, "Dust Reed");
		translationBuilder.add(ModBlocks.VOID_GRASS, "Void Grass");
		translationBuilder.add(ModBlocks.ELDER_CHORUS_WOOD, "Elder Chorus Wood");
		translationBuilder.add(ModBlocks.ELDER_CHORUS_BARK, "Elder Chorus Bark");
		translationBuilder.add(ModBlocks.CHORUS_ROOT, "Chorus Root");
		translationBuilder.add(ModBlocks.CHORUS_MOSS, "Chorus Moss");
		translationBuilder.add(ModBlocks.HOLLOW_CHORUS_WOOD, "Hollow Chorus Wood");
		translationBuilder.add(ModBlocks.HIGHLAND_STONE, "Highland Stone");
		translationBuilder.add(ModBlocks.HIGHLAND_SLATE, "Highland Slate");
		translationBuilder.add(ModBlocks.HIGHLAND_LENSSTONE, "Highland Lensstone");
		translationBuilder.add(ModBlocks.WINDSCAR_BRACKET, "Windscar Bracket");
		translationBuilder.add(ModBlocks.VOID_MARSH_SOIL, "Void Marsh Soil");
		translationBuilder.add(ModBlocks.VOID_REED, "Void Reed");
		translationBuilder.add(ModBlocks.MARSH_MOSS, "Marsh Moss");
		translationBuilder.add(ModBlocks.TIDE_IRON, "Tide Iron");
		translationBuilder.add(ModBlocks.MIREGLASS, "Mireglass");
		translationBuilder.add(ModBlocks.LUMEN_STONE, "Lumen Stone");
		translationBuilder.add(ModBlocks.LUMEN_MOSS, "Lumen Moss");
		translationBuilder.add(ModBlocks.LUMEN_BLOOM, "Lumen Bloom");
		translationBuilder.add(ModBlocks.LUMEN_GRAFT_BLOCK, "Lumen Graft Block");
		translationBuilder.add(ModBlocks.PRISM_CANOPY_BLOCK, "Prism Canopy");
		translationBuilder.add(ModBlocks.ASH_STONE, "Ash Stone");
		translationBuilder.add(ModBlocks.ASHEN_SOIL, "Ashen Soil");
		translationBuilder.add(ModBlocks.CRYSTAL_SHARD_BLOCK, "Crystal Shard Block");
		translationBuilder.add(ModBlocks.CRYSTAL_CLUSTER, "Crystal Cluster");
		translationBuilder.add(ModBlocks.DARK_CRYSTAL_BLOCK, "Dark Crystal Block");
		translationBuilder.add(ModBlocks.PALE_CRYSTAL_BLOCK, "Pale Crystal Block");
		translationBuilder.add(ModBlocks.RESONANT_BASALT, "Resonant Basalt");
		translationBuilder.add(ModBlocks.END_CLAY, "End Clay");
		translationBuilder.add(ModBlocks.VOIDSTONE, "Voidstone");
		translationBuilder.add(ModItems.WASTES_COMPASS, "Wastes Compass");
		translationBuilder.add(ModItems.HIGHLAND_GRAPPLER, "Highland Grappler");
		translationBuilder.add(ModItems.LUMEN_LANTERN, "Lumen Lantern");
		translationBuilder.add(ModItems.VOID_FILTER, "Void Filter");
		translationBuilder.add(ModItems.CRYSTAL_RESONATOR, "Crystal Resonator");
		translationBuilder.add(ModItems.ASH_SIFTER, "Ash Sifter");
		translationBuilder.add(ModItems.CHORUS_PRUNER, "Chorus Pruner");
		translationBuilder.add(ModItems.ARCHIVE_KEY, "Archive Key");
		translationBuilder.add(ModItems.VOID_FLARE, "Void Flare");
		translationBuilder.add(ModItems.END_CARTOGRAPHER, "End Cartographer");
		translationBuilder.add(ModItems.SKYGLASS_SHARD, "Skyglass Shard");
		translationBuilder.add(ModItems.WINDSCAR_WINCH, "Windscar Winch");
		translationBuilder.add(ModItems.MIRE_BELL_CLAPPER, "Mire Bell Clapper");
		translationBuilder.add(ModItems.LUMEN_GRAFT, "Lumen Graft");
		translationBuilder.add(ModItems.PRISM_SEED, "Prism Seed");
		translationBuilder.add(ModItems.CROWN_NEEDLE, "Crown Needle");
		translationBuilder.add(ModItems.CROWN_SEAL, "Crown Seal");
		translationBuilder.add(ModItems.NULL_QUILL, "Null Quill");
		translationBuilder.add(ModItems.THRESHOLD_KEY, "Threshold Key");
		translationBuilder.add(ModItems.DUST_CHITIN, "Dust Chitin");
		translationBuilder.add(ModItems.WASTES_SEED_POD, "Wastes Seed Pod");
		translationBuilder.add(ModItems.STALKER_TENDRIL, "Stalker Tendril");
		translationBuilder.add(ModItems.CHORUS_EYE, "Chorus Eye");
		translationBuilder.add(ModItems.VOID_MEMBRANE, "Void Membrane");
		translationBuilder.add(ModItems.HIGHLAND_FEATHER, "Highland Feather");
		translationBuilder.add(ModItems.VOID_SAP, "Void Sap");
		translationBuilder.add(ModItems.MARSH_TENDRIL, "Marsh Tendril");
		translationBuilder.add(ModItems.CRAWLER_EYE, "Crawler Eye");
		translationBuilder.add(ModItems.LUMEN_DUST, "Lumen Dust");
		translationBuilder.add(ModItems.LUMEN_WING, "Lumen Wing");
		translationBuilder.add(ModItems.WRAITH_ASH, "Wraith Ash");
		translationBuilder.add(ModItems.ASH_CORE, "Ash Core");
		translationBuilder.add(ModItems.BURROWER_PLATE, "Burrower Plate");
		translationBuilder.add(ModItems.CRYSTAL_CORE, "Crystal Core");
		translationBuilder.add(ModItems.CRYSTAL_FANG, "Crystal Fang");
		translationBuilder.add(ModItems.NULL_FRAGMENT, "Null Fragment");
		translationBuilder.add(ModItems.DUST_CRAWLER_SPAWN_EGG, "Dust Crawler Spawn Egg");
		translationBuilder.add(ModItems.CHORUS_STALKER_SPAWN_EGG, "Chorus Stalker Spawn Egg");
		translationBuilder.add(ModItems.VOID_RAY_SPAWN_EGG, "Void Ray Spawn Egg");
		translationBuilder.add(ModItems.MARSH_CRAWLER_SPAWN_EGG, "Marsh Crawler Spawn Egg");
		translationBuilder.add(ModItems.LUMEN_MOTH_SPAWN_EGG, "Lumen Moth Spawn Egg");
		translationBuilder.add(ModItems.ASH_WRAITH_SPAWN_EGG, "Ash Wraith Spawn Egg");
		translationBuilder.add(ModItems.CRYSTAL_BURROWER_SPAWN_EGG, "Crystal Burrower Spawn Egg");
		translationBuilder.add(ModItems.NULLWALKER_SPAWN_EGG, "Nullwalker Spawn Egg");
		translationBuilder.add("entity.endesium.dust_crawler", "Dust Crawler");
		translationBuilder.add("entity.endesium.chorus_stalker", "Chorus Stalker");
		translationBuilder.add("entity.endesium.void_ray", "Void Ray");
		translationBuilder.add("entity.endesium.marsh_crawler", "Marsh Crawler");
		translationBuilder.add("entity.endesium.lumen_moth", "Lumen Moth");
		translationBuilder.add("entity.endesium.ash_wraith", "Ash Wraith");
		translationBuilder.add("entity.endesium.crystal_burrower", "Crystal Burrower");
		translationBuilder.add("entity.endesium.nullwalker", "Nullwalker");
		translationBuilder.add(ModItems.VOID_WISP_SPAWN_EGG, "Void Wisp Spawn Egg");
		translationBuilder.add(ModItems.CROWN_SENTINEL_SPAWN_EGG, "Crown Sentinel Spawn Egg");
		translationBuilder.add("entity.endesium.void_wisp", "Void Wisp");
		translationBuilder.add("entity.endesium.crown_sentinel", "Crown Sentinel");
		translationBuilder.add(ModItems.END_WARDEN_SPAWN_EGG, "End Warden Spawn Egg");
		translationBuilder.add(ModItems.END_GOLEM_SPAWN_EGG, "End Golem Spawn Egg");
		translationBuilder.add("entity.endesium.end_warden", "End Warden");
		translationBuilder.add("entity.endesium.end_golem", "The End Golem");
		translationBuilder.add(ModItems.WARDEN_SIGIL, "Warden Sigil");
		translationBuilder.add(ModItems.GOLEM_CORE, "Golem Core");
		translationBuilder.add(ModItems.GOLEM_EFFIGY, "Golem Effigy");
		translationBuilder.add("advancements.endesium.wardens_bane.title", "Warden's Bane");
		translationBuilder.add("advancements.endesium.wardens_bane.description", "Fell a flagship's End Warden and claim its sigil");
		translationBuilder.add("advancements.endesium.sigil_attuned.title", "Marked by Ten Regions");
		translationBuilder.add("advancements.endesium.sigil_attuned.description", "Attune a Warden Sigil — a heart, forever");
		translationBuilder.add("advancements.endesium.golem_felled.title", "The Engine Falls Silent");
		translationBuilder.add("advancements.endesium.golem_felled.description", "Bring down the End Golem");
		translationBuilder.add("advancements.endesium.core_absorbed.title", "Heavier Than Stone");
		translationBuilder.add("advancements.endesium.core_absorbed.description", "Absorb a Golem Core into yourself");
		translationBuilder.add("advancements.endesium.effigy_ignited.title", "The Engine Wakes Again");
		translationBuilder.add("advancements.endesium.effigy_ignited.description", "Burn a Golem Effigy to re-summon the colossus");
		translationBuilder.add("advancements.endesium.warden_ascendant.title", "Warden Ascendant");
		translationBuilder.add("advancements.endesium.warden_ascendant.description", "Attune all ten regions' sigils");
		translationBuilder.add("advancements.endesium.golems_resolve.title", "Golem's Resolve");
		translationBuilder.add("advancements.endesium.golems_resolve.description", "Absorb ten cores — refuse death once per day");
		translationBuilder.add("biome.endesium.end_wastes", "End Wastes");
		translationBuilder.add("biome.endesium.chorus_wilds", "Chorus Wilds");
		translationBuilder.add("biome.endesium.shattered_highlands", "Shattered Highlands");
		translationBuilder.add("biome.endesium.void_marshes", "Void Marshes");
		translationBuilder.add("biome.endesium.luminous_groves", "Luminous Groves");
		translationBuilder.add("biome.endesium.ashen_expanse", "Ashen Expanse");
		translationBuilder.add("biome.endesium.crystal_barrens", "Crystal Barrens");
		translationBuilder.add("biome.endesium.void_skirts", "Void Skirts");
		translationBuilder.add("biome.endesium.void_crown", "Void Crown");
		translationBuilder.add("biome.endesium.umbral_reach", "Umbral Reach");
		translationBuilder.add(ModItems.VOID_STALKER_SPAWN_EGG, "Void Stalker Spawn Egg");
		translationBuilder.add("entity.endesium.void_stalker", "Void Stalker");
		translationBuilder.add("advancements.endesium.first_resonance.title", "First Resonance");
		translationBuilder.add("advancements.endesium.first_resonance.description", "Activate an ancient Endesium mechanism with the Resonance Lens");
		translationBuilder.add("advancements.endesium.fractured_station.title", "Whispers in the Wastes");
		translationBuilder.add("advancements.endesium.fractured_station.description", "Wake the fractured heart of the Great Caldera");
		translationBuilder.add("advancements.endesium.sunken_archive.title", "The Sunken Archive");
		translationBuilder.add("advancements.endesium.sunken_archive.description", "Descend into the Geode and wake its buried heart");
		translationBuilder.add("advancements.endesium.what_remains.title", "What Remains");
		translationBuilder.add("advancements.endesium.what_remains.description", "Climb the Void Spire and wake its summit core");
		translationBuilder.add("advancements.endesium.the_long_resonance.title", "The Long Resonance");
		translationBuilder.add("advancements.endesium.the_long_resonance.description", "Follow the resonance from a ruin to the tower");
		translationBuilder.add("advancements.endesium.echo_sight.title", "Echo Sight");
		translationBuilder.add("advancements.endesium.echo_sight.description", "Craft an Echo Compass and turn a known signal into a heading");
		translationBuilder.add("advancements.endesium.dragon_transformation.title", "The End Answers");
		translationBuilder.add("advancements.endesium.dragon_transformation.description", "Slay the Dragon and wake the End");
		translationBuilder.add("advancements.endesium.archive_awakened.title", "The Archive Awakens");
		translationBuilder.add("advancements.endesium.archive_awakened.description", "Wake the sealed Null Archive with the Lens");
		translationBuilder.add("advancements.endesium.into_the_wastes.title", "Into the Wastes");
		translationBuilder.add("advancements.endesium.into_the_wastes.description", "Enter the End Wastes");
		translationBuilder.add("advancements.endesium.into_the_wilds.title", "Into the Wilds");
		translationBuilder.add("advancements.endesium.into_the_wilds.description", "Enter the Chorus Wilds");
		translationBuilder.add("advancements.endesium.beyond_the_edge.title", "Beyond the Edge");
		translationBuilder.add("advancements.endesium.beyond_the_edge.description", "Enter the Shattered Highlands");
		translationBuilder.add("advancements.endesium.below_the_surface.title", "Below the Surface");
		translationBuilder.add("advancements.endesium.below_the_surface.description", "Discover the Void Marshes");
		translationBuilder.add("advancements.endesium.follow_the_light.title", "Follow the Light");
		translationBuilder.add("advancements.endesium.follow_the_light.description", "Enter the Luminous Groves");
		translationBuilder.add("advancements.endesium.where_everything_died.title", "Where Everything Died");
		translationBuilder.add("advancements.endesium.where_everything_died.description", "Enter the Ashen Expanse");
		translationBuilder.add("advancements.endesium.heart_of_stone.title", "Heart of Stone");
		translationBuilder.add("advancements.endesium.heart_of_stone.description", "Discover the Crystal Barrens");
		translationBuilder.add("advancements.endesium.something_watches.title", "Something Watches");
		translationBuilder.add("advancements.endesium.something_watches.description", "Encounter the Nullwalker");
		translationBuilder.add("advancements.endesium.scavengers_end.title", "The Scavenger's End");
		translationBuilder.add("advancements.endesium.scavengers_end.description", "Slay a Dust Crawler");
		translationBuilder.add("advancements.endesium.deep_resonance.title", "Deep Resonance");
		translationBuilder.add("advancements.endesium.deep_resonance.description", "Follow a resonance signal to its source");
		translationBuilder.add("advancements.endesium.into_the_skirts.title", "Into the Skirts");
		translationBuilder.add("advancements.endesium.into_the_skirts.description", "Enter the Void Skirts");
		translationBuilder.add("advancements.endesium.void_crown.title", "The Crown");
		translationBuilder.add("advancements.endesium.void_crown.description", "Reach the Void Crown");
		translationBuilder.add("advancements.endesium.umbral_reach.title", "The Umbral Reach");
		translationBuilder.add("advancements.endesium.umbral_reach.description", "Descend into the Umbral Reach");
		translationBuilder.add("advancements.endesium.void_armorer.title", "Voidforged");
		translationBuilder.add("advancements.endesium.void_armorer.description", "Craft a full set of Void armor");
		translationBuilder.add("itemGroup.endesium", "Endesium");

		// Void Skirts items and blocks.
		translationBuilder.add(ModItems.VOID_INGOT, "Void Ingot");
		translationBuilder.add(ModItems.VOID_NUGGET, "Void Nugget");
		translationBuilder.add(ModItems.VOID_GEM, "Void Gem");
		translationBuilder.add(ModItems.UMBRAL_SHARD, "Umbral Shard");
		translationBuilder.add(ModItems.VOID_CORE, "Void Core");
		translationBuilder.add(ModItems.VOID_SWORD, "Void Sword");
		translationBuilder.add(ModItems.VOID_PICKAXE, "Void Pickaxe");
		translationBuilder.add(ModItems.VOID_AXE, "Void Axe");
		translationBuilder.add(ModItems.VOID_SHOVEL, "Void Shovel");
		translationBuilder.add(ModItems.VOID_HOE, "Void Hoe");
		translationBuilder.add(ModItems.VOID_HELMET, "Void Helmet");
		translationBuilder.add(ModItems.VOID_CHESTPLATE, "Void Chestplate");
		translationBuilder.add(ModItems.VOID_LEGGINGS, "Void Leggings");
		translationBuilder.add(ModItems.VOID_BOOTS, "Void Boots");
		translationBuilder.add(ModItems.VOID_COMPASS, "Void Compass");
		translationBuilder.add(ModItems.VOID_ANCHOR, "Void Anchor");
		translationBuilder.add(ModItems.VOID_LANTERN, "Void Lantern");
		translationBuilder.add(ModItems.VOID_DASH, "Void Dash");
		translationBuilder.add(ModBlocks.VOID_SLATE, "Void Slate");
		translationBuilder.add(ModBlocks.CROWN_NEEDLE_BLOCK, "Crown Needle Mast");
		translationBuilder.add(ModBlocks.CROWN_SEAL_BLOCK, "Crown Seal Block");
		translationBuilder.add(ModBlocks.NULL_ARCHIVE_FRAME, "Null Archive Frame");
		translationBuilder.add(ModBlocks.THRESHOLD_CORE_BLOCK, "Threshold Core");
		translationBuilder.add(ModBlocks.VOID_GRAVEL, "Void Gravel");
		translationBuilder.add(ModBlocks.VOID_SOIL, "Void Soil");
		translationBuilder.add(ModBlocks.VOID_GLASS, "Void Glass");
		translationBuilder.add(ModBlocks.VOID_BRICK, "Void Brick");
		translationBuilder.add(ModBlocks.VOID_BRICK_SLAB, "Void Brick Slab");
		translationBuilder.add(ModBlocks.VOID_BRICK_STAIRS, "Void Brick Stairs");
		translationBuilder.add(ModBlocks.VOID_BRICK_WALL, "Void Brick Wall");
		translationBuilder.add(ModBlocks.VOID_LAMP, "Void Lamp");
		translationBuilder.add(ModBlocks.VOID_CRYSTAL, "Void Crystal");
		translationBuilder.add(ModBlocks.UMBRAL_GRASS, "Umbral Grass");
		translationBuilder.add(ModBlocks.VOID_FERN, "Void Fern");
		translationBuilder.add(ModBlocks.VOID_WEAVE, "Void Weave");
		translationBuilder.add(ModBlocks.VOID_SPIRE, "Void Spire");
		translationBuilder.add(ModBlocks.UMBRAL_STONE, "Umbral Stone");
		translationBuilder.add(ModBlocks.VOID_ORE, "Void Ore");
		translationBuilder.add(ModItems.ASHEN_EMBER, "Ashen Ember");
		translationBuilder.add(ModItems.MAGMA_CORE, "Magma Core");
		translationBuilder.add(ModItems.ASHWALKER_BOOTS, "Ashwalker Boots");
		translationBuilder.add(ModItems.EMBER_CHARM, "Ember Charm");
		translationBuilder.add(ModBlocks.ASHEN_CRUST, "Ashen Crust");
		translationBuilder.add("advancements.endesium.heart_of_the_volcano.title", "Heart of the Volcano");
		translationBuilder.add("advancements.endesium.heart_of_the_volcano.description", "Find a dormant volcano in the Ashen Expanse");
		translationBuilder.add("advancements.endesium.ember_walker.title", "Ember Walker");
		translationBuilder.add("advancements.endesium.ember_walker.description", "Walk across lava in Ashwalker Boots");
		translationBuilder.add("advancements.endesium.first_void_shard.title", "First Void Shard");
		translationBuilder.add("advancements.endesium.first_void_shard.description", "Obtain a Void Shard from the deep End");
		translationBuilder.add("advancements.endesium.void_gem_miner.title", "Void Gem Miner");
		translationBuilder.add("advancements.endesium.void_gem_miner.description", "Compress shards into a Void Gem");
		translationBuilder.add("advancements.endesium.void_ingot_smith.title", "Void Ingot Smith");
		translationBuilder.add("advancements.endesium.void_ingot_smith.description", "Smelt a Void Ingot");
		translationBuilder.add("advancements.endesium.void_steel_sword.title", "Void Steel");
		translationBuilder.add("advancements.endesium.void_steel_sword.description", "Forge a Void Sword");
		translationBuilder.add("advancements.endesium.void_skirt_foothold.title", "A Foothold in the Skirts");
		translationBuilder.add("advancements.endesium.void_skirt_foothold.description", "Mine Void Slate");
		translationBuilder.add("advancements.endesium.waste_scavenger.title", "Waste Scavenger");
		translationBuilder.add("advancements.endesium.waste_scavenger.description", "Craft a Wastes Compass");
		translationBuilder.add("advancements.endesium.highland_hook.title", "Highland Hook");
		translationBuilder.add("advancements.endesium.highland_hook.description", "Craft a Highland Grappler");
		translationBuilder.add("advancements.endesium.lumen_beacon.title", "Lumen Beacon");
		translationBuilder.add("advancements.endesium.lumen_beacon.description", "Craft a Lumen Lantern");
		translationBuilder.add("advancements.endesium.crystal_tuner.title", "Crystal Tuner");
		translationBuilder.add("advancements.endesium.crystal_tuner.description", "Craft a Crystal Resonator");
		translationBuilder.add("advancements.endesium.ash_prospector.title", "Ash Prospector");
		translationBuilder.add("advancements.endesium.ash_prospector.description", "Craft an Ash Sifter");
		translationBuilder.add("advancements.endesium.wild_tender.title", "Wild Tender");
		translationBuilder.add("advancements.endesium.wild_tender.description", "Craft a Chorus Pruner");
		translationBuilder.add("advancements.endesium.archive_seeker.title", "Archive Seeker");
		translationBuilder.add("advancements.endesium.archive_seeker.description", "Craft an Archive Key");
		translationBuilder.add("advancements.endesium.void_signal.title", "Void Signal");
		translationBuilder.add("advancements.endesium.void_signal.description", "Craft a Void Flare");
		translationBuilder.add("advancements.endesium.end_cartographer_done.title", "End Cartographer");
		translationBuilder.add("advancements.endesium.end_cartographer_done.description", "Craft an End Cartographer");
		translationBuilder.add("advancements.endesium.dragonbone_carver.title", "Dragonbone Carver");
		translationBuilder.add("advancements.endesium.dragonbone_carver.description", "Obtain Dragonbone");
	}

	@Override
	public String getName() {
		return "Endesium production language";
	}
}
