#!/usr/bin/env bash
# Feeds world-generation verification commands to the dedicated server after
# it has finished booting, then shuts it down. Piped into the gradle runServer
# task as stdin.
set -u
BOOT_SLEEP="${1:-110}"
sleep "$BOOT_SLEEP"
# Force a chunk near spawn in the End to be generated by the console itself
echo "execute in minecraft:the_end run setblock 0 70 0 minecraft:end_stone"
sleep 2
echo "execute in minecraft:the_end run locate biome endesium:end_wastes"
sleep 3
echo "execute in minecraft:the_end run locate biome endesium:chorus_wilds"
sleep 3
echo "execute in minecraft:the_end run locate biome minecraft:end_highlands"
sleep 3
echo "execute in minecraft:the_end run locate structure minecraft:end_city"
sleep 3
echo "execute in minecraft:the_end run locate structure minecraft:end_gateway"
sleep 2
echo "stop"
sleep 5
